### ISSUE TITLE
Cannot change position in Organizer

### ISSUE THREAD

**Issue by goerz** [luoliyan/incremental-reading#81] opened 2018-10-19 17:30 UTC
I'm not completely sure if I'm running into a bug (I think so) or whether I misunderstand how the IR plugin is supposed to be used.

When I go to the Organizer (⌥2), I get a list of imported articles which I think is in the order that I imported them in:

![image](https://user-images.githubusercontent.com/112306/47233470-dc5b5000-d3a0-11e8-9cbe-a5203a81e35c.png)

When I select one of the entries, and use the Up or Down buttons, the item moves, but the number in front of it doesn't change:

![image](https://user-images.githubusercontent.com/112306/47233562-25130900-d3a1-11e8-9cd2-be814d14a0ad.png)

When I click "Save", restart Anki, and open the Organizer again, everything is back to the original order. That is, nothing I do permanently changes the order in the list.

Moreover, when I review IR cards, they are always shown in the exact order of the numbers in the Organizer list. When I click "Show Answer", and click the "Soon" or "Later" button, I see a message like "Card moved to position 4" pop up in the bottom of the screen, but this doesn't seem to be reflected in the Organizer list, or in what is shown the next time I review IR cards. The "Custom" button doesn't seem to do anything besides bringing up the Organizer. This sounds like a bug, right?

Incidentally, regarding my above screenshots: what do those stacked bars to the left and right of each number indicate? Why are some rows bigger than others? Why are there line breaks in item 8?

While I'm here, trying to figure out this plugin: It seems like on the Mac, IR cards always stay as "New" after reviewing them. Is this intentional? When I access the cards on the iOS client, however, I don't have the "Soon" or "Later" button, but instead the same "1m", "10m", "4d" buttons that I get for regular cards, and changes the status of the cards from "New" to "Reviewed". This status then gets synced back to the Mac. Thus, will opening my IR deck on iOS just screw up the cards, and should be avoided?

**Specs:**
 - OS: macOS 10.13.6
 - Anki Version v2.1.5
- Incremental Reading Version v4913

**Comment by goerz** [comment] 2018-10-22 04:19
So for some reason it magically started working: I can now reorder entries in the Organizer, and when I click response buttons "Soon", "Later" the articles move in the Organizer as indicated in the popup. I'm not sure what changed. Maybe the contents of some card?

In any case, feel free to close this issue, or keep it open if you think the "fix" would be better documentation on how the Organizer is intended to work (as my problem was partly that I didn't know what to expect as "correct" behavior)

**Comment by luoliyan** [comment] 2018-10-24 11:46
I can answer _most_ of those questions.

The stacked bars aren't supposed to be there. It's a font issue:
![screenshot_20181024_205356](https://user-images.githubusercontent.com/24988028/47427330-2a23ee00-d7cf-11e8-821f-a41ef74a9e00.png)
Possibly your font doesn't support those Unicode characters. I just thought those were more readable than ASCII brackets, but maybe that was too cheeky.

I don't know why some lines are bigger than others, or why entry number 8 is broken up. There are probably linebreaks in the text, which I thought should be stripped out. I'll try to fix that.

The cards should always be marked "new". They do not enter the standard Anki scheduler because they need to be managed differently from spaced repetition cards. I agree that's confusing.

As for iOS, that is the expected behaviour, but not the desired behaviour. It's unavoidable, though. On the desktop, the add-on disables the Anki scheduler for IR cards. The iOS client doesn't have add-ons, so they are treated as SRS cards.

Part of the reason the add-on seems a bit confusing is because _it is_ a bit confusing. Some of the design decisions were made in the really early days, before I rewrote the add-on. I've tried not to break too much of the old behaviour because I know that would affect some people. For example, the organiser launching when you press "custom" is actually the original behaviour. I rewrote the organiser, but it is still invoked in the some ways.

I'm going to leave this open because there are several legitimate issues here.

**Comment by luoliyan** [comment] 2018-10-31 14:30
Most of this is addressed in the latest version.

- You can now customise the formatting of the organiser (if your font still doesn't want to play nice with ❰ and ❱, you can change them).
- The note titles breaking across lines was _probably_ due to a bunch of spaces. Those should be stripped out now.

I'll also try to put more explanation in the readme (or maybe add some pages to the wiki?) to address the points of confusion.

**Closed by luoliyan** 2018-10-31 14:30 UTC
Labels: bug, enhancement, question

**Comment by luoliyan** [comment] 2018-10-31 14:35
Not uploaded to AnkiWeb yet, by the way. Give me a few days to make sure I haven't broken anything :-)

(You can test the GitHub version if you like.)

**Comment by goerz** [comment] 2018-10-31 14:39
Wonderful, thanks!

Personally, I've actually come to the conclusion that IR works better for me without the reading list (which I've removed in my forked version of your plugin). Instead, I'm using the regular Anki scheduler, but with heavy customization of the options for that deck (Max 10 reviews/day, 500% easy bonus, 80% interval modifier, and 90 days max interval). That gives me something like what I was describing in 
https://github.com/burtonator/polar-bookshelf/issues/309. It also makes the system compatible with the iPad (except I can't use the shortcuts for highlighting and extraction, but I can work around that).

Nonetheless, your fix (and general work on this plugin) is greatly appreciated, and together with more documentation on the wiki I hope a lot more people will be using this.

**Comment by luoliyan** [comment] 2018-10-31 15:48
I'll probably add an option to disable the IR scheduler. It never occurred to me that people might want SRS for IR cards.
