### ISSUE TITLE
error on answering cloze card

### ISSUE THREAD

**Issue by snoyes** [luoliyan/incremental-reading#88] opened 2018-12-12 15:20 UTC
A cloze card created from the add-on shows the question correctly, then pops up the following on the answer side:

Debug info:
Anki 2.1.5 Python 3.6.1 Qt 5.9.2 PyQt 5.9
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "aqt\webview.py", line 295, in handler
  File "aqt\reviewer.py", line 461, in _onTypedAnswer
  File "aqt\reviewer.py", line 222, in _showAnswer
  File "anki\hooks.py", line 28, in runHook
  File "C:\Users\scnoyes\AppData\Roaming\Anki2\addons21\935264945\main.py", line 134, in onShowAnswer
    mw.stateShortcuts.remove(qs)
<class 'ValueError'>: list.remove(x): x not in list

**Comment by luoliyan** [comment] 2018-12-14 16:43
Thanks. From memory, this has happened inconsistently for some time. I'll look into it over the weekend.

**Comment by luoliyan** [comment] 2019-04-21 13:22
This is probably a duplicate of #63, which I still haven't got around to addressing. I'll close this but keep the older report open.

**Closed by luoliyan** 2019-04-21 13:22 UTC
Labels: bug
