### ISSUE TITLE
Bug: Invalid HTML on card: TypeError: require is not a function

### ISSUE THREAD

**Issue by aronneagu** [luoliyan/incremental-reading#55] opened 2018-02-12 23:18 UTC
I have Anki Version 2.1.0beta36 and Incremental addon version 4.7.14.

I added the the source code from https://aws.amazon.com/ec2/faqs/ to a an IR3 note: in the Text field, I pressed "Edit HTML", and added the source code of the above page. However, when I tried to read the article, I got the following error "Invalid HTML on card: TypeError: require is not a function"

I am running MacOS 10.12.6
Below you can see the order in which I tried to open the IR3 notes.

Do I have to downgrade to Anki 2.0? Any help would be appreciated. Thank you.
<img width="524" alt="screen shot 2018-02-12 at 23 16 39" src="https://user-images.githubusercontent.com/1262715/36125179-e943099e-104a-11e8-9013-090fa77fe650.png">
<img width="524" alt="screen shot 2018-02-12 at 23 16 43" src="https://user-images.githubusercontent.com/1262715/36125177-e793e906-104a-11e8-88fd-b769c728aaa9.png">
<img width="524" alt="screen shot 2018-02-12 at 23 16 47" src="https://user-images.githubusercontent.com/1262715/36125174-e652666c-104a-11e8-8779-774c7d0866d2.png">

**Comment by TimotheeChauvin** [comment] 2018-02-13 08:21
I'm not Luo Li-Yan, however if I understood the code correctly this is not the correct way to import a webpage. The right way is through `Alt + 3` or *Read -> Import webpage*. This way the tags 'script' (script) and 'iframe' (embedded webpage) and their contents are removed from the html (this operation is done with BeautifulSoup4 and html.parser).
In your case, the error seems to come from several 'script' tags that weren't removed.

However, the fun thing is that I got a completely new kind of issue with your webpage (and the correct procedure): the note is totally blank in Anki (in review state), but my mouse can detect links and they work, and if I edit it everything seems to be fine in the 'Text' field. I waited during one minute, thinking that perhaps the content was loading, but it didn't solve the problem.
![image](https://user-images.githubusercontent.com/34207828/36139260-20ef8a82-109d-11e8-9e24-d9b290931dfd.png)

![image](https://user-images.githubusercontent.com/34207828/36139341-68d29e8e-109d-11e8-8021-78778926f4ec.png)

(Anki 2.1.0beta27, Linux, not really IR v4.8.0 so perhaps I've messed up some part of the code but I think it's more likely that the error comes from this particular page's html)

**Comment by luoliyan** [comment] 2018-02-13 11:45
Hi,

Timothee is basically correct. In my experience, the "invalid HTML on card" is usually embedded JavaScript. IR will strip this out when using "Import Webpage".

I will try to identify what part of your webpage is causing rendering errors, and see if that can be stripped out automatically. The only things that were really causing me trouble were iframes and scripts, so that is all that IR strips out at the moment. I'm happy to add other things to the blacklist, though.

Thanks for the report.

**Comment by luoliyan** [comment] 2018-02-13 12:51
Okay. This is caused by a conditional statement in the HTML. I've solved this by automatically stripping all comments.

This change is complete locally. I'll close this now, and upload the fix in the next few days.

**Closed by luoliyan** 2018-02-13 12:51 UTC
Labels: bug

**Comment by aronneagu** [comment] 2018-02-13 12:54
Thank you for the prompt reply and fix. Its great to see such activity on the issue tracker. 
Keep the good work, its an awesome plugin.
